### ISSUE TITLE
Composer - debug enabled for default.

### ISSUE THREAD

**Issue by mwarzynski** [webnull-archived-projects/panthera#363]
I noticed that we are using debugging in composer for default.

As warning states:
`You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug`
So, we should disable it in case we are working in productive environment...

**Comment by webnull** [comment]
I know but currently I don't know if we could turn it off ;)
It depends probably on PHP settings.
